test:
	eval $(luarocks path)
	busted

download:
	wget https://www.lua.org/ftp/lua-5.3.6.tar.gz
	tar -xzf lua-5.3.6.tar.gz
	wget https://luarocks.org/releases/luarocks-3.9.2.tar.gz
	tar -xzf luarocks-3.9.2.tar.gz
